version: '3.8'

services:
  # Development React Application
  logistics-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SUPABASE_URL=${SUPABASE_URL}
      - REACT_APP_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - REACT_APP_ENVIRONMENT=development
      - REACT_APP_DEBUG_MODE=true
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - supabase-db
    networks:
      - logistics-network

  # Local Supabase Database
  supabase-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: logistics_hospital
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d
    networks:
      - logistics-network

  # Supabase Studio for development
  supabase-studio:
    image: supabase/studio:latest
    ports:
      - "54323:3000"
    environment:
      SUPABASE_URL: http://supabase-db:5432
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
    depends_on:
      - supabase-db
    networks:
      - logistics-network

  # Redis for development caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - logistics-network

volumes:
  postgres_data:
  redis_data:

networks:
  logistics-network:
    driver: bridge
